#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '^src/' | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Remove leading 'src/' from paths because container mounts src at /app
FILES_IN_CONTAINER=$(echo "$FILES" | sed 's|^src/||')

# Prettify all selected files
echo "$FILES_IN_CONTAINER" | xargs docker compose exec -T payload npx prettier --ignore-unknown --write --color

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
