import type { Post } from '@/payload-types'

export const post3: Partial<Post> = {
  slug: 'dollar-and-sense',
  slugLock: false,
  _status: 'published',
  // @ts-expect-error string value will be replaced with the actual ID when seeding
  authors: ['{{AUTHOR}}'],
  content: {
    root: {
      type: 'root',
      children: [
        {
          type: 'block',
          fields: {
            blockName: 'Haftungsausschluss',
            blockType: 'banner',
            content: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Haftungsausschluss: ',
                        version: 1,
                      },
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Dieser Inhalt ist fiktiv und dient nur zu Demonstrationszwecken. Um diesen Beitrag zu bearbeiten, ',
                        version: 1,
                      },
                      {
                        type: 'link',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'navigieren Sie zum Admin-Dashboard.',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        fields: {
                          linkType: 'custom',
                          newTab: true,
                          url: '/admin',
                        },
                        format: '',
                        indent: 0,
                        version: 3,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    textFormat: 1,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            style: 'info',
          },
          format: '',
          version: 2,
        },
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Geld ist nicht nur Währung; ',
              version: 1,
            },
            {
              type: 'text',
              detail: 0,
              format: 2,
              mode: 'normal',
              style: '',
              text: 'es ist eine Sprache. ',
              version: 1,
            },
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Tauchen Sie tief in seine Nuancen ein, wo Strategie auf Intuition im weiten Meer der Finanzen trifft.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Geld überschreitet in seinem Wesen das bloße Konzept von Münzen und Papierscheinen; es wird zu einer tiefsinnigen Sprache, die von Wert, Vertrauen und gesellschaftlichen Strukturen spricht. Wie jede Sprache besitzt es komplexe Nuancen und Feinheiten, die ein unterscheidendes Verständnis erfordern. In diesen Tiefen kollidiert die kalkulierte Welt der Finanzstrategie mit der rohen, instinktiven Natur der menschlichen Intuition. So wie ein erfahrener Linguist die Syntax und Semantik eines Satzes sezieren könnte, navigiert ein Finanzexperte durch den weiten und turbulenten Ozean der Finanzen, geleitet nicht nur von Logik und Daten, sondern auch von Bauchgefühl und Weitsicht. Jede Transaktion, Investition und finanzielle Entscheidung wird zu einem Dialog in diesem umfassenden Lexikon von Handel und Wert.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
        {
          type: 'block',
          fields: {
            blockName: '',
            blockType: 'mediaBlock',
            media: '{{IMAGE_2}}',
            position: 'default',
          },
          format: '',
          version: 2,
        },
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Aktienmarktdynamik: Bullen, Bären und die unsichere Mitte',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Der Aktienmarkt ist ein Bereich großer Chancen, birgt aber auch Risiken. Entdecken Sie die Kräfte, die Markttrends antreiben, und die Strategien, die von Top-Händlern angewendet werden, um dieses komplexe Ökosystem zu navigieren. Von der Marktanalyse bis zum Verständnis der Anlegerpsychologie erhalten Sie einen umfassenden Einblick in die Welt der Aktien.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Der Aktienmarkt, oft als geschäftige Arena von Zahlen und Tickerbändern visualisiert, dreht sich ebenso um menschliches Verhalten wie um Wirtschaft. Es ist ein Ort, an dem Optimismus, repräsentiert durch die bullische Rally, auf die Vorsicht der bärischen Abschwünge trifft, wobei jeder versucht, die Richtung des Marktes zu diktieren. Doch zwischen diesen beiden Extremen liegt eine unsichere Mitte, eine Zone, die von Händlern und Anlegern bevölkert wird, die ständig Hoffnung gegen Angst abwägen. Eine erfolgreiche Navigation erfordert mehr als nur finanzielles Geschick; sie verlangt ein Verständnis kollektiver Gefühle und die Fähigkeit, nicht nur Marktbewegungen vorherzusagen, sondern auch die Reaktionen anderer Marktteilnehmer. In diesem komplizierten Tanz aus Zahlen und Nerven sind die scharfsinnigsten Akteure diejenigen, die sowohl die harten Daten als auch die feinen Nuancen des menschlichen Verhaltens beherrschen.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
        {
          type: 'block',
          fields: {
            blockName: 'Dynamische Komponenten',
            blockType: 'banner',
            content: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Der obige Inhalt ist vollständig dynamisch und verwendet benutzerdefinierte Layout-Bausteine, die im CMS konfiguriert sind. Dies kann alles sein, von Rich Text und Bildern bis hin zu hochgradig gestalteten, komplexen Komponenten.',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            style: 'info',
          },
          format: '',
          version: 2,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  meta: {
    description: `Geld ist nicht nur Währung; es ist eine Sprache. Tauchen Sie tief in seine Nuancen ein, wo Strategie auf Intuition im weiten Meer der Finanzen trifft.`,
    // @ts-expect-error string value will be replaced with the actual ID when seeding
    image: '{{IMAGE_1}}',
    title: 'Dollar und Sinn: Die Finanzprognose',
  },
  relatedPosts: [], // wird durch das Seed-Skript befüllt
  title: 'Dollar und Sinn: Die Finanzprognose',
}

export const post3_en: Partial<Post> = {
  slug: 'dollar-and-sense',
  slugLock: false,
  _status: 'published',
  // @ts-expect-error string value will be replaced with the actual ID when seeding
  authors: ['{{AUTHOR}}'],
  content: {
    root: {
      type: 'root',
      children: [
        {
          type: 'block',
          fields: {
            blockName: 'Disclaimer',
            blockType: 'banner',
            content: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Disclaimer: ',
                        version: 1,
                      },
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'This content is fabricated and for demonstration purposes only. To edit this post, ',
                        version: 1,
                      },
                      {
                        type: 'link',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'navigate to the admin dashboard.',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        fields: {
                          linkType: 'custom',
                          newTab: true,
                          url: '/admin',
                        },
                        format: '',
                        indent: 0,
                        version: 3,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    textFormat: 1,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            style: 'info',
          },
          format: '',
          version: 2,
        },
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: "Money isn't just currency; ",
              version: 1,
            },
            {
              type: 'text',
              detail: 0,
              format: 2,
              mode: 'normal',
              style: '',
              text: "it's a language. ",
              version: 1,
            },
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Dive deep into its nuances, where strategy meets intuition in the vast sea of finance.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: "Money, in its essence, transcends the mere concept of coins and paper notes; it becomes a profound language that speaks of value, trust, and societal structures. Like any language, it possesses intricate nuances and subtleties that require a discerning understanding. It's in these depths where the calculated world of financial strategy collides with the raw, instinctive nature of human intuition. Just as a seasoned linguist might dissect the syntax and semantics of a sentence, a financial expert navigates the vast and tumultuous ocean of finance, guided not only by logic and data but also by gut feelings and foresight. Every transaction, investment, and financial decision becomes a dialogue in this expansive lexicon of commerce and value.",
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
        {
          type: 'block',
          fields: {
            blockName: '',
            blockType: 'mediaBlock',
            media: '{{IMAGE_2}}',
            position: 'default',
          },
          format: '',
          version: 2,
        },
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Stock Market Dynamics: Bulls, Bears, and the Uncertain Middle',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'The stock market is a realm of vast opportunity but also poses risks. Discover the forces that drive market trends and the strategies employed by top traders to navigate this complex ecosystem. From market analysis to understanding investor psychology, get a comprehensive insight into the world of stocks.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: "The stock market, often visualized as a bustling arena of numbers and ticker tapes, is as much about human behavior as it is about economics. It's a place where optimism, represented by the bullish rally, meets the caution of bearish downturns, with each vying to dictate the market's direction. But between these two extremes lies an uncertain middle ground, a zone populated by traders and investors who constantly weigh hope against fear. Successful navigation requires more than just financial acumen; it demands an understanding of collective sentiments and the ability to predict not just market movements, but also the reactions of other market participants. In this intricate dance of numbers and nerves, the most astute players are those who master both the hard data and the soft nuances of human behavior.",
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
        {
          type: 'block',
          fields: {
            blockName: 'Dynamic components',
            blockType: 'banner',
            content: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: "This content above is completely dynamic using custom layout building blocks configured in the CMS. This can be anything you'd like from rich text and images, to highly designed, complex components.",
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            style: 'info',
          },
          format: '',
          version: 2,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  meta: {
    description: `Money isn't just currency; it's a language. Dive deep into its nuances, where strategy meets intuition in the vast sea of finance.`,
    // @ts-expect-error string value will be replaced with the actual ID when seeding
    image: '{{IMAGE_1}}',
    title: 'Dollar and Sense: The Financial Forecast',
  },
  relatedPosts: [], // this is populated by the seed script
  title: 'Dollar and Sense: The Financial Forecast',
}
